---

apiVersion: v1
kind: Service
metadata:
  name: visit-nodeport
  labels:
    app: visit
  annotations:
    # these are the annotations that kube-consul-register will look for in order
    # to determine if it should register.
    #
    # We also override the name so it doesn't include the guid associated
    # with this replicaset.
    consul.register/enabled: 'true'
    consul.register/service.name: 'visit-nodeport'
spec:
  type: NodePort
  ports:
  - port: 80
  selector:
    app: visit
