apiVersion: v1
kind: Service
metadata:
  name: consul
  labels:
    app: consul
spec:
  ports:
  - name: http
    port: 8500
    targetPort: 8500
  - name: dns
    port: 8600
    targetPort: 8600
  selector:
    app: consul

---

apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: consul
spec:
  selector:
    matchLabels:
      app: consul
  replicas: 1
  template:
    metadata:
      labels:
        app: consul
    spec:
      containers:
      - name: master
        image: consul
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        command: 
          - consul
          - agent
          - -dev
          - -client
          - 0.0.0.0
        ports:
        - name: http
          containerPort: 8500
        - name: dns
          containerPort: 8600
