apiVersion: v1
data:
    VISIT_HOST: "0.0.0.0"
    VISIT_PORT: "80"
    VISIT_REDISADDR: "redis-master:6379"
    VISIT_REDISKEY: "visit.count"
kind: ConfigMap
metadata:
    name: visit
    namespace: default

---

apiVersion: v1
kind: Service
metadata:
  name: visit
  labels:
    app: visit
  annotations:
    # these are the annotations that kube-consul-register will look for in order
    # to determine if it should register.
    #
    # We also override the name so it doesn't include the guid associated
    # with this replicaset.
    consul.register/enabled: 'true'
    consul.register/service.name: 'visit'
spec:
  type: NodePort 
  ports:
  - port: 80
  selector:
    app: visit

---

apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: visit
spec:
  selector:
    matchLabels:
      app: visit
  replicas: 3
  template:
    metadata:
      labels:
        app: visit
        tier: frontend
    spec:
      containers:
      - name: visit
        image: partkyle/go-visit:0.4.0
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        envFrom:
        - configMapRef:
            name: visit
        ports:
        - containerPort: 80
